[package]
name = "meminfo"
version = "0.1.0"
authors = ["joshua <kjkq26993@gaia.eonet.ne.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
